package com.davanddev.quizapp_api.models;
import jakarta.persistence.*;

/**
 * Entity class representing a quiz result.
 */
@Entity
@Table(name = "results")
public class QuizResult {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", columnDefinition = "INT GENERATED BY DEFAULT AS IDENTITY")
    private int id;

    /**
     * The user who took the quiz.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The course name for which the quiz was taken.
     */
    @Column(name = "course_name")
    private String courseName;

    /**
     * The score achieved by the user.
     */
    @Column(name = "score")
    private int score;

    /**
     * The total number of questions in the quiz.
     */
    @Column(name = "total_questions")
    private int totalQuestions;

    /**
     * Default constructor required by Hibernate.
     */
    public QuizResult() {}

    /**
     * Constructs a QuizResult with the specified parameters.
     *
     * @param user           the User who took the quiz.
     * @param courseName     the name of the course.
     * @param score          the score achieved.
     * @param totalQuestions the total number of questions.
     */
    public QuizResult(User user, String courseName, int score, int totalQuestions) {
        this.user = user;
        this.courseName = courseName;
        this.score = score;
        this.totalQuestions = totalQuestions;
    }

    /**
     * Returns the identifier of the quiz result.
     *
     * @return the quiz result id.
     */
    public int getId() {
        return id;
    }

    /**
     * Returns the associated User.
     *
     * @return the User entity.
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the associated User.
     *
     * @param user the User entity to set.
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * Returns the course name.
     *
     * @return the course name.
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * Sets the course name.
     *
     * @param courseName the course name to set.
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /**
     * Returns the score.
     *
     * @return the score.
     */
    public int getScore() {
        return score;
    }

    /**
     * Sets the score.
     *
     * @param score the score to set.
     */
    public void setScore(int score) {
        this.score = score;
    }

    /**
     * Returns the total number of questions.
     *
     * @return the total number of questions.
     */
    public int getTotalQuestions() {
        return totalQuestions;
    }

    /**
     * Sets the total number of questions.
     *
     * @param totalQuestions the total number of questions to set.
     */
    public void setTotalQuestions(int totalQuestions) {
        this.totalQuestions = totalQuestions;
    }
}
