package com.davanddev.quizapp_api.models;

import jakarta.persistence.*;
import java.util.Objects;

/**
 * Entity class representing a user.
 */
@Entity
@Table(name = "users")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", columnDefinition = "INT GENERATED BY DEFAULT AS IDENTITY")
    private int id;

    private String username;

    /**
     * Default constructor required by JPA.
     */
    public User() {}

    /**
     * Constructs a User with the specified username.
     *
     * @param username the username.
     */
    public User(String username) {
        this.username = username;
    }

    /**
     * Constructs a User with the specified id and username.
     *
     * @param id       the user id.
     * @param username the username.
     */
    public User(int id, String username) {
        this.id = id;
        this.username = username;
    }

    /**
     * Returns the user id.
     *
     * @return the id.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the user id.
     *
     * @param id the id to set.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the username.
     *
     * @return the username.
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the username.
     *
     * @param username the username to set.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof User)) return false;
        User user = (User) o;
        return id == user.id && Objects.equals(username, user.username);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, username);
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", username='" + username + '\'' +
                '}';
    }
}
